name: Create a mod release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: "Refresh tags"
        id: tag
        run: git fetch --tags --force

      - uses: ericcornelissen/git-tag-annotation-action@v2.0.6
        id: tag-data

      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3.0.1
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          release_text: ${{ steps.tag-data.outputs.git-tag-annotation }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}